version: '3'
services:
  frontend:
    container_name: "front"
    hostname: "frontend"
    build: ./front
    ports: 
      - "3030:3030"
    depends_on:
      - db
    command: './wait-for db:3306 --timeout=100 -- npm run admin'
    environment:
      - DATABASE_HOST=db
  db:
    container_name: "database"
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=hackerman06
      - MYSQL_DATABASE=xssinject
    ports:
      - "3306:3306"
      
    